Dare-test-umb8/Models/LoginModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Dare_test_umb8.Models
{
    public class LoginModel
    {
        [Display(Name = "Username")]
        [Required]
        public string Username { get; set; }

        [Display(Name = "Password")]
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

Dare-test-umb8/Controllers/MemberController.cs
using Dare_test_umb8.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Umbraco.Web.Mvc;

namespace Dare_test_umb8.Controllers
{
    public class MemberController : SurfaceController
    {
        public ActionResult RenderLogin()
        {
            return PartialView("_Login", new LoginModel());
        }

        [System.Web.Http.HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitLogin(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (Membership.ValidateUser(model.Username, model.Password))
                {
                    FormsAuthentication.SetAuthCookie(model.Username, false);
                    return Redirect("/to-do/");
                 
                }
                else
                {
                    ModelState.AddModelError("", "The username or password provided is incorrect.");
                }
            }
            return CurrentUmbracoPage();
        }

        public ActionResult RenderLogout()
        {
            return PartialView("_Logout", null);
        }

        public ActionResult SubmitLogout()
        {
            TempData.Clear();
            Session.Clear();
            FormsAuthentication.SignOut();
            return RedirectToCurrentUmbracoPage();
        }
    }
}

Dare-test-umb8/Views/Challenge.cshtml
    @inherits Umbraco.Web.Mvc.UmbracoViewPage<Umbraco.Web.PublishedModels.Challenge>
    @using Clean.Core.ViewModels
    @using Clean.Core.Extensions

    @{
    Layout = "master.cshtml";
    }

    @Html.Partial("~/Views/Partials/pageHeader.cshtml", new PageHeaderViewModel(Model.Name, Model.Title, Model.Subtitle, Model.MainImage))

    <article>
        @Html.GetGridHtml(Model, "mainContent", "Clean", fluidImages: true)
    </article>

Dare-test-umb8/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Login>
    @using Clean.Core.ViewModels
    @using Clean.Core.Extensions
    @using ContentModels = Umbraco.Web.PublishedModels;
    @{
    Layout = "master.cshtml";
    }



    @Html.Partial("~/Views/Partials/pageHeader.cshtml", new PageHeaderViewModel(Model.Name, Model.Title, Model.Subtitle, Model.MainImage))

    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                @{ Html.RenderAction("RenderLogin","Member"); }
            </div>
        </div>
    </div>

Dare-test-umb8/Views/NotAuthorised.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.NotAuthorised>
    @using Clean.Core.ViewModels
    @using Clean.Core.Extensions
    @using ContentModels = Umbraco.Web.PublishedModels;
    @{
    Layout = "master.cshtml";
    }

Dare-test-umb8/Views/Partials/BlockList/Default.cshtml
@inherits UmbracoViewPage<BlockListModel>
@using Umbraco.Core.Models.Blocks
@{
    if (!Model.Any()) { return; }
}
<div class="umb-block-list">
    @foreach (var block in Model)
    {
        if (block?.ContentUdi == null) { continue; }
        var data = block.Content;
        @Html.Partial("BlockList/Components/" + data.ContentType.Alias, block)        
    }
</div>

Dare-test-umb8/Views/Partials/Contact/contactForm.cshtml
@inherits UmbracoViewPage<ContactViewModel>

@using Clean.Core.ViewModels
@using Clean.Core.SurfaceControllers

<div id="form-outer">
    @using (Ajax.BeginForm("SubmitForm", "Contact", new AjaxOptions()
    {
        UpdateTargetId = "form-result",
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        OnSuccess = "contactForm.showResult",
        OnFailure = "contactForm.showResult"
    }, new { id = "contact-form" }))
    {

        <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label>@Umbraco.GetDictionaryValue("ContactForm.Name")</label>
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.Name)

                <p class="help-block text-danger"></p>
            </div>
        </div>
        <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label>@Umbraco.GetDictionaryValue("ContactForm.Email")</label>
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
                @Html.ValidationMessageFor(m => m.Email)
                <p class="help-block text-danger"></p>
            </div>
        </div>
        <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label>@Umbraco.GetDictionaryValue("ContactForm.Message")</label>
                @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Message", rows = "6" })
                @Html.ValidationMessageFor(m => m.Message)
                <p class="help-block text-danger"></p>
            </div>
        </div>
        <br>
        <div class="form-group">
            <button type="submit" class="btn btn-primary" id="sendMessageButton">@Umbraco.GetDictionaryValue("ContactForm.Send")</button>
        </div>
    }
</div>
<div id="form-result"></div>

Dare-test-umb8/Views/Partials/Contact/result.cshtml
@inherits UmbracoViewPage<IHtmlString>
    
@Model

Dare-test-umb8/Views/Partials/Grid/Bootstrap3-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row);
                    }
                </div>
            }   
        }else { 
            <div class="row clearfix">
                @foreach (var s in Model.sections) {
                    <div class="grid-section">
                        <div class="col-md-@s.grid column">
                            @foreach (var row in s.rows) {
                                @renderRow(row);
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@helper renderRow(dynamic row){
    <div @RenderElementAttributes(row)>
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Dare-test-umb8/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }
        }else {
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Html.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Html.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Dare-test-umb8/Views/Partials/Grid/Clean.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @foreach (var section in Model.sections)
        {
            <div class="grid-section">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 col-md-10 mx-auto">
                            @foreach (var row in section.rows)
                            {
                                @renderRow(row, true)
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        <div class="row">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Dare-test-umb8/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

Dare-test-umb8/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

Dare-test-umb8/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

Dare-test-umb8/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;
    
    <img src="@url" alt="@altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

Dare-test-umb8/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Composing
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString(), Current.UmbracoContext.UrlProvider))

Dare-test-umb8/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Composing
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();
    markup = markup.Replace("#value#", Html.ReplaceLineBreaksForHtml(HttpUtility.HtmlEncode((string)Model.value.ToString())).ToString());

    if (Model.editor.config.style != null)
    {
        markup = markup.Replace("#style#", Model.editor.config.style.ToString());
    }

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

Dare-test-umb8/Views/Partials/_login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Dare_test_umb8.Models.LoginModel>
@using Umbraco.Web

@if (!Umbraco.MemberIsLoggedOn())
{

    using (Html.BeginUmbracoForm("SubmitLogin", "Member", System.Web.Mvc.FormMethod.Post, new { id = "login" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.LabelFor(m => m.Username)
            @Html.TextBoxFor(m => m.Username, new { @class = "form-control", placeholder = "Enter email" })
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Password)
            @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Password" })

        </div>

        <button name="login" class="btn btn-primary" type="submit">Login</button>

        @Html.ValidationSummary()

    }
}
else
{
    Html.RenderAction("RenderLogout", "Member");
}

Dare-test-umb8/Views/Partials/_logout.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using Umbraco.Web

@if (Umbraco.MemberIsLoggedOn())
{
    using (Html.BeginUmbracoForm("SubmitLogout", "Member", System.Web.Mvc.FormMethod.Post, new { id = "logout" }))
    {
        @Html.AntiForgeryToken()
        var myUser = System.Web.Security.Membership.GetUser();
        if (myUser != null)
        {
            <p><strong>Logged in as</strong> <span>@myUser.UserName</span></p>
            <button name="login" type="submit"><span>logout</span> <i class="fa fa-arrow-right"></i></button>
        }
    }
}

Dare-test-umb8/Views/Partials/footer.cshtml
@inherits UmbracoViewPage

@{
    var homePage = Model.AncestorOrSelf<Home>();
}

<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                @if (homePage.SocialLinks != null && homePage.SocialLinks.Any())
                {
                    <ul class="list-inline text-center">
                        @foreach (var item in homePage.SocialLinks)
                        {
                            <li class="list-inline-item">
                                <a href="@item.Link.Url" target="@item.Link.Target" title="@item.Link.Name">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="@item.IconClass fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        }
                    </ul>
                }
                <p class="copyright text-muted">@Umbraco.GetDictionaryValue("Footer.CopyrightTitle") &copy; @DateTime.Now.Year @Umbraco.GetDictionaryValue("Footer.CopyrightStatement")</p>
               
            </div>
        </div>
    </div>
</footer>

Dare-test-umb8/Views/Partials/latestArticles.cshtml
@inherits UmbracoViewPage

@using Clean.Core.Helpers

@{
    var articleList = UmbracoContext.Content.GetAtRoot().DescendantsOrSelf<ArticleList>().FirstOrDefault();
    var isArticleListPage = Model.Id == articleList.Id;
    var fallbackPageSize = isArticleListPage ? 10 : 3;

    var pageSize = QueryStringHelper.GetIntFromQueryString(Request, "size", fallbackPageSize);
    var pageNumber = QueryStringHelper.GetIntFromQueryString(Request, "page", 1);
    var allArticles = articleList.Children<Article>().Where(x => x.IsVisible()).OrderByDescending(x => x.ArticleDate);
    var pageOfArticles = allArticles.Skip((pageNumber - 1) * pageSize).Take(pageSize);
    var totalItemCount = allArticles.Count();
    var pageCount = totalItemCount > 0 ? Math.Ceiling((double)totalItemCount / pageSize) : 1;

}

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            @foreach (var article in pageOfArticles)
            {
                <div class="post-preview">
                    <a href="@article.Url">
                        <h2 class="post-title">
                            @(!string.IsNullOrWhiteSpace(article.Title) ? article.Title : article.Name)
                        </h2>
                        @if (!string.IsNullOrWhiteSpace(article.Subtitle))
                        {
                            <h3 class="post-subtitle">@article.Subtitle</h3>
                        }
                    </a>
                    <p class="post-meta">
                        @Umbraco.GetDictionaryValue("Article.Posted")
                        @if (!string.IsNullOrWhiteSpace(article.AuthorName))
                        {
                            @Umbraco.GetDictionaryValue("Article.By")@Html.Raw("&nbsp;")@article.AuthorName
                        }
                        @Umbraco.GetDictionaryValue("Article.On") @article.ArticleDate.ToString("MMMM dd, yyyy")
                    </p>
                </div>
                <hr>
            }
            <!-- Pager -->
                <div id="paging" class="clearfix">
                    @if (isArticleListPage)
                    {
                        if (pageCount > 1)
                        {
                            <div class="paging-block">
                                @if (pageNumber > 1)
                                {
                                <a class="btn btn-primary float-left" href="@($"{articleList.Url}?page={pageNumber - 1}&size={pageSize}")">@Umbraco.GetDictionaryValue("Paging.Previous")</a>
                                }
                                else
                                {
                                    @Html.Raw("&nbsp;")
                                }
                            </div>
                            <div class="paging-block text-center">
                                <span>@Umbraco.GetDictionaryValue("Paging.Page") @pageNumber @Umbraco.GetDictionaryValue("Paging.Of") @pageCount</span>
                            </div>
                            <div class="paging-block">
                                @if (pageNumber < pageCount)
                                {
                                <a class="btn btn-primary float-right" href="@($"{articleList.Url}?page={pageNumber + 1}&size={pageSize}")">@Umbraco.GetDictionaryValue("Paging.Next")</a>
                                }
                                else
                                {
                                    @Html.Raw("&nbsp;")
                                }
                            </div>

                        }
                    }
                    else
                    {
                        <a class="btn btn-primary float-right" href="@(articleList.Url)">@Umbraco.GetDictionaryValue("ArticleList.ViewAll")</a>
                    }
                </div>
        </div>
    </div>
</div>

Dare-test-umb8/Views/Partials/mainNavigation.cshtml
@inherits UmbracoViewPage

@{
    var homePage = Model.AncestorOrSelf<Home>();
}

<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="@homePage.Url">@Umbraco.GetDictionaryValue("Navigation.SiteName")</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            @Umbraco.GetDictionaryValue("Navigation.MenuTitle")
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@homePage.Url">@homePage.Name</a>
                </li>
                @foreach (var page in homePage.Children.Where(x => !x.Value<bool>
    ("umbracoNaviHide")))
    {
    <li class="nav-item">
        <a class="nav-link" href="@page.Url">@page.Name</a>
    </li>
    }

    @* show login logout button *@
    @if (!Umbraco.MemberIsLoggedOn())
    {
                
    <li class="nav-item">
        <a class="nav-link" href="/login">Login </a>
    </li>
    }
    else{
    <li class="nav-item">
        @using (Html.BeginUmbracoForm("SubmitLogout", "Member", System.Web.Mvc.FormMethod.Post, new { id = "logout" }))
        {
        Html.AntiForgeryToken();
        var myUser = System.Web.Security.Membership.GetUser();
        if (myUser != null)
        {
        <button class="btn btn-primary" name="login" type="submit"><span>logout</span></button>
        }
        }
    </li>
    }
</ul>
        </div>
    </div>
</nav>

Dare-test-umb8/Views/Partials/metaData.cshtml
@inherits UmbracoViewPage<IPublishedContent>

@{
    var homePage = Model.AncestorOrSelf<Home>();
    string domainAddress = homePage.Url(mode:UrlMode.Absolute).TrimEnd('/');
    string canonicalLink = domainAddress + Model.Url;
    string metaName = Model.Value<string>("metaName");
    string metaDescription = Model.Value<string>("metaDescription");
    var metaKeywords = Model.Value<IEnumerable<string>>("metaKeywords");
}

<meta charset="utf-8" />
<link rel="icon" type="image/png" href="/media/favicon.png">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<title>
    @string.Format("{0} | {1}", Model.Name, Umbraco.GetDictionaryValue("Navigation.SiteName"))
</title>
<meta name="Description" content="@metaDescription" />
<meta name="Name" content="@metaName" />
<meta name="Keywords" content="@string.Join(",", metaKeywords)" />
<link rel="canonical" href="@canonicalLink" />

<meta property="og:type" content="article" />
<meta property="og:url" content="@canonicalLink" />
<meta property="og:title" content="@metaName" />
<meta property="og:description" content="@metaDescription" />
<meta property="og:image" content="@(domainAddress)/socialimage.png">
<meta property="og:image:type" content="image/png">

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="@metaName">
<meta name="twitter:description" content="@metaDescription">
<meta name="twitter:image" content="@(domainAddress)/socialimage.png">

<link rel="apple-touch-icon" sizes="57x57" href="/media/favicon.png?width=57&height=57">
<link rel="apple-touch-icon" sizes="60x60" href="/media/favicon.png?width=60&height=60">
<link rel="apple-touch-icon" sizes="72x72" href="/media/favicon.png?width=72&height=72">
<link rel="apple-touch-icon" sizes="76x76" href="/media/favicon.png?width=76&height=76">
<link rel="apple-touch-icon" sizes="114x114" href="/media/favicon.png?width=114&height=114">
<link rel="apple-touch-icon" sizes="120x120" href="/media/favicon.png?width=120&height=120">
<link rel="apple-touch-icon" sizes="144x144" href="/media/favicon.png?width=144&height=144">
<link rel="apple-touch-icon" sizes="152x152" href="/media/favicon.png?width=152&height=152">
<link rel="apple-touch-icon" sizes="180x180" href="/media/favicon.png?width=180&height=180">

Dare-test-umb8/Views/TestCanvas.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.TestCanvas>
    @using ContentModels = Umbraco.Web.PublishedModels;
    @using Clean.Core.ViewModels
    @using Clean.Core.Extensions
    @{
    Layout = "master.cshtml";
    }


    @Html.Partial("~/Views/Partials/pageHeader.cshtml", new PageHeaderViewModel(Model.Name, Model.Title, Model.Subtitle, Model.MainImage))

    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div id="root"></div>
                </div>
            </div>
    </div>
                
    @section scripts{    
    <script src="~/frontend/dist/scripts/index.js"></script>
    }